[package]
name = "endgame"
description = "A turn-based game engine."
authors = ["Geoffrey Washburn <geoff@washburght.org>"]
version = "0.1.0"
keywords = ["game", "engine", "gamedev"]
license = "MIT"
repository = "https://github.com/gawashburn/endgame"
exclude = ["crates/"]
edition = "2024"


[workspace]
resolver = "2"
members = [
    "crates/*",
    # Examples have not yet been migrated.
    #    "examples/*"
]

[dependencies]
endgame_direction = { path = "crates/endgame_direction" }
