[package]
name = "endgame"
description = "A turn-based game engine."
authors = ["Geoffrey Washburn <geoff@washburght.org>"]
version = "0.1.0"
license = "MIT"
repository = "https://github.com/gawashburn/endgame"
edition = "2024"

[dependencies]
