name: Deploy Pages

on:
  workflow_run:
    workflows: [ "Tests" ]
    types: [ completed ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Create dist directory
        run: |
          mkdir ${{ runner.temp }}/dist

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Select Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Ensure wasm32 target installed
        run: rustup target add wasm32-unknown-unknown

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install trunk
        uses: jetli/trunk-action@v0.5.1
        with:
          version: 'latest'

      - name: Create grid_demo directory
        run: |
          mkdir ${{ runner.temp }}/dist/grid_demo

      - name: Build grid_demo with trunk
        working-directory: examples/grid_demo
        run: trunk build --release --no-sri --public-url https://gawashburn.github.io/endgame/grid_demo --dist ${{ runner.temp }}/dist/grid_demo

      - name: Upload Pages artifact (dist)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ runner.temp }}/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
