name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Coverage

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Select toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Test with coverage
        run: cargo llvm-cov --all --all-features --no-fail-fast  --lcov --output-path lcov.info
        env:
          CARGO_INCREMENTAL: '0'
      - name: Coveralls upload
        uses: coverallsapp/github-action@v2
        with:
          path-to-lcov: ${{ steps.coverage.outputs.report }}
